apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fluxtest
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/krishs50/fluxtest.git